---
- name: Prelim Exam
  hosts: ubuntu-1920195

  tasks:
    - name: Run config.yaml
      include_vars:
        file: config.yaml

    - name: Role 1
      include_role:
        name: python3

    - name: Role 2
      include_role:
        name: java
    
    - name: Role 3
      include_role:
        name: change-motd

    - name: Role 4
      include_role:
        name: create-user
